# AppVeyor CI build configuration for c-blosc

# Before cloning the repo, configure git to handle line endings correctly.
init:
  - git config --global core.autocrlf input

# This is the build version displayed on AppVeyor's UI.
# It's incrementally automatically like travis-ci but allows custom formatting.
version: '{build}'

build_script:
  - cmd: build.bat

test_script:
  - cmd: build.bat All
