# AppVeyor CI build configuration for facio.

# Use VS2015 VM image, since facio is using some F# 4.0 features.
os: Visual Studio 2015

# Before cloning the repo, configure git to handle line endings correctly.
init:
  - git config --global core.autocrlf input

# This is the build version displayed on AppVeyor's UI.
# It's incrementally automatically like travis-ci but allows custom formatting.
version: '{build}'

build_script:
  - cmd: build.bat

test_script:
  - cmd: build.bat All
